### ISSUE TITLE
Is it supporting RTL languages or abjad characters?

### ISSUE THREAD

**Issue by Xoshbin** [tigitz/php-spellchecker#12]
Hi, I just started testing this library for Kurdish language. but when started testing I found out that it's not supporting RTL languages. I did even test "PHP pspell" alone without this library.  it was not working too. I know there's no dictionary files for Kurdish language, but I tried using custom dictionaries but it looks like none of them accept abjad characters in the first place. is there's any explanation to that please? 
Thanks

**Comment by tigitz** [comment]
Hello @Xoshbin 

Thanks for giving a try to the library.

As the library is a wrapper around existing spellchecking engines, if the one you use supports RTL languages and Kurdish language then it should be fine. 

As long as the Abjad characters are utf8 encoded the library doesn't get in your way.

If the 2 points above are not true, then it's a bug.

I'll investigate and come back to you.

**Comment by tigitz** [comment]
**I've tried persian with LanguageTools:**

Start the spellchecking engine using docker:
```bash
docker run -d --rm -p 8010:8010 silviof/docker-languagetool 
```

languagetools_persian_example.php
```php
<?php

use PhpSpellcheck\Spellchecker\LanguageTool;
use PhpSpellcheck\Spellchecker\LanguageTool\LanguageToolApiClient;

require_once __DIR__ . '/../vendor/autoload.php';

// *** Using spellcheckers directly ***
$spellchecker = new LanguageTool(
    new LanguageToolApiClient('http://localhost:8010')
); // Creates aspell spellchecker pointing to "aspell" as it's binary path

/** @var \PhpSpellcheck\Misspelling[]|\Generator $misspellings */
$misspellings = $spellchecker->check(<<<TEXT
لطفا متن خود را اینجا قرار دهید . یا بررسی کنید که این متن را‌ برای دیدن بعضی بعضی از اشکال هایی که ابزار زبان توانسته تشخیس هدد. درباره ی نرم افزارهای بررسی کننده های گرامر چه فکر می کنید؟ لطفا در نظر داشته باشید که آن‌ها بی نقص نمی باشند.‎
TEXT
, ['fa'], ['from' => 'languagetool spellchecker']);
foreach ($misspellings as $misspelling) {
    print_r([
        $misspelling->getWord(),
        $misspelling->getLineNumber(),
        $misspelling->getOffset(),
        $misspelling->getSuggestions(),
        $misspelling->getContext(),
    ]);
}
```

and it worked as expected :heavy_check_mark: 

**I've also tried with an arabic dictionary for hunspell**

Install arabic hunspell dictionaries:
```bash
$ apt-get install hunspell-ar
```

```php
<?php

use PhpSpellcheck\Spellchecker\Aspell;

require_once __DIR__ . '/../vendor/autoload.php';

// *** Using spellcheckers directly ***
$hunspell = \PhpSpellcheck\Spellchecker\Hunspell::create(); // Creates aspell spellchecker pointing to "aspell" as it's binary path

/** @var \PhpSpellcheck\Misspelling[]|\Generator $misspellings */
$misspellings = $hunspell->check('هدف مشروع آيسبل هو إنشاء قواميس في اللغة العربية للتطبيقات المكتبية الحرة مثل مجموعة أوبن أوفس', ['ar'], ['from' => 'aspell spellchecker']);
foreach ($misspellings as $misspelling) {
    print_r([
        $misspelling->getWord(),
        $misspelling->getLineNumber(),
        $misspelling->getOffset(),
        $misspelling->getSuggestions(),
        $misspelling->getContext(),
    ]);
}
```

and it worked too :heavy_check_mark: 

<hr>

I would advise to make sure the spellchecking engine you chose is working as expected by running it through the command line first.

Then if it works on the command line and not through the library please feel free to reopen the issue. Meanwhile I'll close it :slightly_smiling_face:
