### ISSUE TITLE
Process with command "'hunspell' '-a' '-d' 'en_US'" has failed running with exit code 1(General error)

### ISSUE THREAD

**Issue by warmwhisky** [tigitz/php-spellchecker#23]
Upon trying the first example in the docs "Using the spellchecker directly" I get the following error
`Process with command "'hunspell' '-a' '-d' 'en_US'" has failed running with exit code 1(General error)`
```// if you made the default hunspell installation on you local machine
$hunspell = Hunspell::create();

// en_US hunspell dictionary is available
$misspellings = $hunspell->check('mispell', ['en_US'], ['from_example']);
foreach ($misspellings as $misspelling) {
    $misspelling->getWord(); // 'mispell'
    $misspelling->getLineNumber(); // '1'
    $misspelling->getOffset(); // '0'
    $misspelling->getSuggestions(); // ['misspell', ...]
    $misspelling->getContext(); // ['from_example']
}
```
Upon checking installed dictionaries from Laravel I get the following error which is strange because from command line it works(see last code block for `hunspell -D`
`Process with command "'hunspell' '-D'" has failed running with exit code 1(General error)`
```
$hunspell = Hunspell::create();

$hunspell->getSupportedLanguages();
```

I tried first with Aspell and got the same error. 

Do you have any pointers as to where the issue might be coming from?

Linux Mint 20
PHP 7.4
Laravel 6.20.16
I found that both Aspell and Hunspell were already installed on Linux mint. 
```
$ aspell -v
@(#) International Ispell Version 3.1.20 (but really Aspell 0.60.8)
$ hunspell -v
@(#) International Ispell Version 3.2.06 (but really Hunspell 1.7.0)
```

```
$ hunspell -D
SEARCH PATH:
.::/usr/share/hunspell:/usr/share/myspell:/usr/share/myspell/dicts:/Library/Spelling:/home/USERNAME/.openoffice.org/3/user/wordbook:/home/USERNAME/.openoffice.org2/user/wordbook:/home/USERNAME/.openoffice.org2.0/user/wordbook:/home/USERNAME/Library/Spelling:/opt/openoffice.org/basis3.0/share/dict/ooo:/usr/lib/openoffice.org/basis3.0/share/dict/ooo:/opt/openoffice.org2.4/share/dict/ooo:/usr/lib/openoffice.org2.4/share/dict/ooo:/opt/openoffice.org2.3/share/dict/ooo:/usr/lib/openoffice.org2.3/share/dict/ooo:/opt/openoffice.org2.2/share/dict/ooo:/usr/lib/openoffice.org2.2/share/dict/ooo:/opt/openoffice.org2.1/share/dict/ooo:/usr/lib/openoffice.org2.1/share/dict/ooo:/opt/openoffice.org2.0/share/dict/ooo:/usr/lib/openoffice.org2.0/share/dict/ooo
AVAILABLE DICTIONARIES (path is not mandatory for -d option):
/usr/share/hunspell/en_CA
/usr/share/hunspell/en_ZA
/usr/share/hunspell/es_US
/usr/share/hunspell/es_SV
/usr/share/hunspell/en_AU
/usr/share/hunspell/es_VE
/usr/share/hunspell/es_NI
/usr/share/hunspell/pt_PT
/usr/share/hunspell/pt_BR
/usr/share/hunspell/es_BO
/usr/share/hunspell/es_PA
/usr/share/hunspell/es_PY
/usr/share/hunspell/es_HN
/usr/share/hunspell/en_GB
/usr/share/hunspell/es_CU
/usr/share/hunspell/de_DE
/usr/share/hunspell/de_CH_frami
/usr/share/hunspell/es_CO
/usr/share/hunspell/fr_CH
/usr/share/hunspell/fr
/usr/share/hunspell/de_DE_frami
/usr/share/hunspell/de_AT_frami
/usr/share/hunspell/es_PR
/usr/share/hunspell/es_AR
/usr/share/hunspell/de_AT
/usr/share/hunspell/es_UY
/usr/share/hunspell/en_US
/usr/share/hunspell/fr_FR
/usr/share/hunspell/fr_CA
/usr/share/hunspell/it_CH
/usr/share/hunspell/de_CH
/usr/share/hunspell/ru_RU
/usr/share/hunspell/es_ES
/usr/share/hunspell/es_DO
/usr/share/hunspell/fr_LU
/usr/share/hunspell/es_GT
/usr/share/hunspell/es_CL
/usr/share/hunspell/es_MX
/usr/share/hunspell/fr_BE
/usr/share/hunspell/fr_MC
/usr/share/hunspell/es_CR
/usr/share/hunspell/it_IT
/usr/share/hunspell/es_EC
/usr/share/hunspell/es_PE
/usr/share/myspell/dicts/fr_CH
/usr/share/myspell/dicts/hyph_ru_RU
/usr/share/myspell/dicts/fr_FR
/usr/share/myspell/dicts/fr_CA
/usr/share/myspell/dicts/fr_LU
/usr/share/myspell/dicts/fr_BE
/usr/share/myspell/dicts/fr_MC
```

**Comment by tigitz** [comment]
Hey @warmwhisky,

Sorry for being late on this issue, didn't receive any notification.

This is indeed weird, tests are passing on the CI with regular Debian docker image.

Could you try to execute `echo 'mispell' | hunspell -i utf-8 -a -d en_US` on the command line and give me the output.

Hunspell class is more or less running this command when spellchecking so if it works on the command line then we'll have to focus our investigation on the lib side.

Btw if the lib has been helpful to you don't hesitate to star the project, thanks !

**Comment by tigitz** [comment]
Closing untill new infos

**Comment by nlarrosa** [comment]
Hello, how are you, I wanted to know if they could solve it, the same thing happens to me and I can't find the solution. Thank you!

**Comment by tigitz** [comment]
Could you try to execute `echo 'mispell' | hunspell -i utf-8 -a -d en_US` on the command line and give me the output.

Hunspell class is more or less running this command when spellchecking so if it works on the command line then we'll have to focus our investigation on the lib side.

Also could you give me the output of composer info -i.

**Comment by alketii** [comment]
Hi, I am having the same problem. This is the output of:

echo 'mispell' | hunspell -i utf-8 -a -d en_US
@(#) International Ispell Version 3.2.06 (but really Hunspell 1.7.1)
& mispell 4 0: misspell, mi spell, mi-spell, spell

**Comment by tigitz** [comment]
Hey @alketii, seems like there's an issue on php call side then.
If you can debug what's the error output of the console command ran while spellchecking and post it here that would be helpful. 

In the meantime, I'll try to improve the exception by gathering more information about the error to ease debugging in a next version. I'll keep you updated.

**Comment by alketii** [comment]
Could you help me with the command, I am not sure which one to run.

**Comment by alketii** [comment]
I was able to pinpoint the problem.
I am using Mac and it has zsh shell. I install hunspell with Homebrew and the PATH of hunspell was set only at zsh, not to sh which PHP uses.

**Comment by tigitz** [comment]
@alketii wow, thanks for your investigation.

Now I'm wondering how to solve this 🤔

Did you find a solution to use the current shell instead of the `sh` one?

**Comment by alketii** [comment]
I looked into changing the shell but with no luck.
I ended up changing line 93 of Spellchecker/Hunspell.php to the full path of hunspell
` return new self(new CommandLine($binaryPathAsString ?? '/opt/homebrew/bin/hunspell'));`

Since the production uses Linux, I didn't put much thought.
