### ISSUE TITLE
Hunspell class doesn't work in web

### ISSUE THREAD

**Issue by Webakula** [tigitz/php-spellchecker#26]
## Detailed description
It does not work outside of CLI.
In cli **hunspell someword** and laravel artisan command with Hunspell::create() works fine, but in controller (http layer) it always returns empty array. Why?
## Your environment
Ubuntu 20.04
PHP 8.0.6
Laravel 8.50

###Code sample

```
use PhpSpellcheck\Spellchecker\Hunspell;

        $spell = Hunspell::create();


        $misspellings = $spell->check($this->argument('phrase'), ['ru'], ['from_example']);
        $arr = [];
        foreach ($misspellings as $misspelling) {
            $arr[$misspelling->getWord()] = $misspelling->getSuggestions();
        }
```

How to fix that? Thanks!

**Comment by tigitz** [comment]
Hello @Webakula 

I've pushed some changes in `0.2.1`. Just run `composer update` and tell me if it fix the problem for you.

Thanks

**Comment by tigitz** [comment]
Closing as there's no feedback. Open a new issue if issue is not fixed on your side.
