### ISSUE TITLE
Utf8 issue not fixed in master

### ISSUE THREAD

**Issue by devoided** [tigitz/php-spellchecker#28]
I am having issues with Aspell incorrectly reading UTF-8 strings.

You fixed this with [this commit](https://github.com/tigitz/php-spellchecker/commit/54d94bb6024a63ba82a3891f324c6602aeb1f1e9#diff-c2a62d6f9388b23ed45f96e87aa336e16ff9b788c59d34b0cdf023f1b45aee8b)

Unfortunately, composer is not pulling this commit into the main package.

Is there any way I can pull this working fix into my project?

**Comment by tigitz** [comment]
Hello, I just tagged master with 0.2.2, you can now do a `composer update` and benefit from the fix.
