### ISSUE TITLE
t() function in src/Text/functions.php prevents use with Drupal

### ISSUE THREAD

**Issue by sonfd** [tigitz/php-spellchecker#41]
Drupal has a default built-in function t(). As soon as I `composer require tigitz/php-spellchecker`, the site stops working because we have two definitions of the function t().

## Detailed description
It looks like this is just a shortcut for `new Text()` and is used only a few times, and only in examples and tests.

## Context
Why is this change important to you? How would you use it?
I would like to use this library in a Drupal project.

How can it benefit other users?
Others could too...

## Possible implementation
Drop it - its only purpose is to save 7 key strokes. Or namespace it.

**Comment by tigitz** [comment]
Thanks for your report.

I'm leaning towards fixing it by namespacing it right now.

Both approaches seem reasonable, having to write a lot of `new Text` can 
feel tedious and `t()` can make code more readable and more efficient to type for some developers. While others don't see the point and are fine with using `new Text` everywhere.

symfony/string has `s()`, Drupal has `t()` and Laravel has many helper functions including some one letter one.

So I would like to keep both to please everyone but of course without interfering with other popular packages like you reported.

I'll take the weekend to ponder and make the decision.

**Comment by sonfd** [comment]
Thanks @tigitz - have a nice weekend :)

**Comment by tigitz** [comment]
Thanks again @sonfd for your report, I've published release https://github.com/tigitz/php-spellchecker/releases/tag/0.5.0 that would fix your issue.

I'm closing but feel free to reopen if it doesn't seem to be fixed on your hand.
