### ISSUE TITLE
Process with command "'aspell' '--encoding' 'utf-8' '-a' '--lang=en_US'" has failed running with exit code 127

### ISSUE THREAD

**Issue by hassanfayyaz19** [tigitz/php-spellchecker#44]
## Detailed description

when I create object of aspell its throw an exception
`$query = request()->input('term');`
`$misspellings = $aspell->check($query, ['en_US']);`
` return response()->json($misspellings);`

* PHP 8:
* Window 10
* Laravel 9
* Docker

**Comment by tigitz** [comment]
Hello, I see you're using windows and docker. I didn't tested this setup but using the aspell requires the aspell binary to be available.

If your run your php from the docker container, aspell must be installed in your container too.

Check the installation instructions here:
https://tigitz.github.io/php-spellchecker/docs/spellcheckers/aspell.html

If it's installed, try running `'aspell' '--encoding' 'utf-8' '-a' '--lang=en_US'` in the docker container and paste the result here.

**Comment by hassanfayyaz19** [comment]
i resolved it by adding `aspell` and `aspell-en` in my container
```
docker exec -ti container-name ash
apk add aspell
apk add aspell-en
```
