### ISSUE TITLE
Possible error in hunspell.php

### ISSUE THREAD

**Issue by arcanaer** [tigitz/php-spellchecker#49]
Hello, i think that you have an error in hunspell.php line 68, we need to get the error output, but we have an exception, i've modified the code, to:
```
public function getSupportedLanguages(): iterable
    {
        $languages = [];
        $cmd = $this->binaryPath->addArg('-D');
        $process = new Process($cmd->getArgs());
        $process->run();
        $output = explode(PHP_EOL, $process->getErrorOutput());
```

The error is when you use the multiple spell checker with hunspell and language tools.

**Comment by tigitz** [comment]
Hello, I'm not able to reproduce the exception.

[I've even introduced an integration test](https://github.com/tigitz/php-spellchecker/commit/30dfe2d44d39eb387e344bd2404c5e3ca725c821) for MultiSpellchecker::getSupportedLanguages() using real implementation of LanguageTools and Hunspell.

Could you paste here the exception output please.
